version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/ftkm/app
      - /ftkm/app/node_modules
    env_file:
      - .env
    # Внешний порт:внутренний порт
    ports:
      - 8089:8089
    environment:
      # установка порта запуска приложения
      - PORT=8089
      # установка uri подключения к mongo db
      - MONGO_URI=mongodb://mongo:27017/ftkm
    depends_on:
      - mongo
    networks:
      - db_network
    restart: always

# Database config
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:  
      - dbdata:/data/db
    networks:
      - db_network
    restart: always
    
# Client config
  frontend:
    build: ../frontend
    container_name: frontend
    # Внешний порт:внутренний порт
    ports:
    - '3000:3000'
    restart: always

networks:
  db_network:
    driver: bridge
volumes:
  dbdata:
  node_modules: