version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/ftkm/app
      - /ftkm/app/node_modules
    env_file:
      - .env
    ports:
      - 8089:8089
    environment:
      # установка порта запуска приложения
      - PORT=8089
      # установка uri подключения к mongo db
      - MONGO_URI=mongodb://mongo:27017/ftkm
    depends_on:
      - mongo
    networks:
      - db_network
    restart: unless-stopped

# Database config
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:  
      - dbdata:/data/db
    networks:
      - db_network
    restart: unless-stopped
# Client config
  client:
    build: ../client
    container_name: client
    ports:
    - '8090:8090'

networks:
  db_network:
    driver: bridge
volumes:
  dbdata:
  node_modules: